// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Paper struct {
	ArxivID      string    `json:"arxiv_id"`
	Title        string    `json:"title"`
	Abstract     string    `json:"abstract"`
	Authors      string    `json:"authors"`
	ShortAuthors string    `json:"short_authors"`
	Date         time.Time `json:"date"`
}

type SavedPaper struct {
	ID      int64          `json:"id"`
	UserID  sql.NullInt64  `json:"user_id"`
	PaperID sql.NullString `json:"paper_id"`
}

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}
