// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePaper(ctx context.Context, arxivID string) error
	DeleteSavedPaper(ctx context.Context, arg DeleteSavedPaperParams) error
	GetPaper(ctx context.Context, arxivID string) (Paper, error)
	GetPapers(ctx context.Context, arg GetPapersParams) ([]Paper, error)
	GetSavedPapersForUser(ctx context.Context, arg GetSavedPapersForUserParams) ([]SavedPaper, error)
	GetUser(ctx context.Context, id int64) (User, error)
	SavePaperForUser(ctx context.Context, arg SavePaperForUserParams) (SavedPaper, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
